language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5

matrix:
    exclude:
        - python: "3.2"
          env: DJANGO=1.2.7
        - python: "3.2"
          env: DJANGO=1.3.7
        - python: "3.2"
          env: DJANGO=1.4.5

        - python: "3.3"
          env: DJANGO=1.2.7
        - python: "3.3"
          env: DJANGO=1.3.7
        - python: "3.3"
          env: DJANGO=1.4.5

        - python: "pypy"
          env: DJANGO=1.2.7
        - python: "pypy"
          env: DJANGO=1.3.7

        # pypy 1.9 can't run tests with django 1.5
        - python: "pypy"
          env: DJANGO=1.5


install:
  - pip install django==$DJANGO --use-mirrors
  - pip install coverage coveralls --use-mirrors
  - python setup.py install

script: coverage run runtests.py --source widget_tweaks

after_success:
  - coveralls
