language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

env:
  - DJANGO = 'django >=1.2, <1.3'
  - DJANGO = 'django >=1.3, <1.4'
  - DJANGO = 'django >=1.4, <1.5'
  - DJANGO = 'django >=1.5, <1.6'

matrix:
    exclude:
        - python: "3.2"
          env: DJANGO = 'django >=1.2, <1.3'
        - python: "3.2"
          env: DJANGO = 'django >=1.3, <1.4'
        - python: "3.2"
          env: DJANGO = 'django >=1.4, <1.5'

        - python: "3.3"
          env: DJANGO = 'django >=1.2, <1.3'
        - python: "3.3"
          env: DJANGO = 'django >=1.3, <1.4'
        - python: "3.3"
          env: DJANGO = 'django >=1.4, <1.5'

        - python: "pypy"
          env: DJANGO = 'django >=1.2, <1.3'
        - python: "pypy"
          env: DJANGO = 'django >=1.3, <1.4'


install:
  - pip install coverage coveralls --use-mirrors
  - pip install $DJANGO --use-mirrors
  - python setup.py install

script: coverage run runtests.py --source widget_tweaks

after_success:
  - coveralls
